#travis ci config script


language: cpp

compiler:
  - clang
  - gcc

before_install:
  - uname -a
  - lsb_release -a
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test     # gcc 4.8
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports       # cmake >=2.8.10
  - sudo add-apt-repository --yes ppa:fkrull/deadsnakes           # python3.3
  - sudo apt-add-repository --yes ppa:sfttech/opusfile            # opusfile
  - sudo apt-get update -qq

install:
  - export CVERSION="4.8"
  - sudo apt-get install -qq g++-${CVERSION}; #also needed for newer stdlib
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${CVERSION}" CC="gcc-${CVERSION}"; fi
  - export CC=`which $CC`
  - export CXX=`which $CXX`
  - sudo apt-get install -qq python3.3 python3.3-dev libglew-dev libftgl-dev libfreetype6-dev libfontconfig1-dev libsdl2-dev libsdl2-image-dev libopusfile-dev cmake

before_script:
  - git pull --unshallow    # the full git history is required for 'make checkfull'
  - cmake --version
  - ls -l /usr/bin/python*
  - sudo ln -sf /usr/bin/python3.3 /usr/bin/python3
  - python3 --version

script:
  - ./configure
  - make openage    # running 'make'/'make all' would cause 'make check' to run after building
  - make runtest    # running 'make test' would cause 'make check' to run after testing
  - make checkfull  # manually run 'make checkfull'

after_script:
  - echo test build exited

notifications:
#  recipients:
#    - lol@mail.ie
#    - rofl@liam.ei
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#sfttech"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
    use_notice: true
    skip_join: true

#static analysis with coverty
env:
  global:
   - secure: "CK04R9TuA+gFFMBvyTw0DKbhr8wDnZY5wTTNs5CylArGAyzokHUr7tDRislQdJhvB4QI2rzIEuH3priHdPacl58ftwHL6Zy8tl3ByvUpGoN+XLHHw9TZP1gHK0S9bFwRcZdXyWNxZjudYvJDTbK7IwWuv/+HC2Ie/x161k4qeHc="

#addons:
#  coverity_scan:
#    project:
#      name: "SFTtech/openage"
#      description: "free age of empires 2 engine"
#    notification_email: openage+coverty@sft.mx
#    build_command_prepend: "./configure"
#    build_command: "make"
#    branch_pattern: master
